## Import

In [75]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.49)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.12)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [76]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


from sqlalchemy import create_engine

## Read data

In [77]:
data = pd.read_csv("https://raw.githubusercontent.com/dewitrilestari/BLKPP-DIY-VS-CODE/refs/heads/main/vgsales.csv")
data

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [78]:
data.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [79]:
data.tail()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.0,0.0,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.0,0.0,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.0,0.0,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.0,0.0,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.0,0.0,0.01

## Connect to SQL

In [80]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "postgres.wrprbwghsiweangcbxmb"
password = quote_plus("Dedew123!@Tri")
host = "aws-1-ap-southeast-2.pooler.supabase.com"
port = "6543"
database = "postgres"

DATABASE_URL = (
    f"postgresql://{username}:{password}@{host}:{port}/{database}"
)

engine = create_engine(DATABASE_URL)

In [81]:
data.to_sql('vgsales', con=engine, schema='public', if_exists='replace', index=False)

598

#Business Understanding

Data tersebut menunjukkan data penjualan video  game berdasarkan rank (menunjukkan peminat terbanyak), nama game, platform, genre, publisher, tahun rilis, dan penjualan di berbagai wilayah di dunia (NA_Sales menunjukkan penjualan di wilayah North America atau Amerika Utara, EU_Sales menunjukkan penjualan di wilayah Europe atau Eropa, JP_Sales menunjukkan penjualan di wilayah Japan atau Jepang, Other_Sales menunjukkan penjualan di wilayah lain, dan Global_Sales menunjukkan penjualan secara global). Satuan total penjualan video game dalam satuan juta unit sehingga jumlah penjualan tersebut ditampilkan dalam berapa juta copy yang sudah terjual. 0,01 menunjukkan 10 ribu juta copy yang sudah terjual.

# Data Understanding

In [82]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

In [83]:
data.describe()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16327.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,2006.406443,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.853933,5.828981,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

Nilai mean dan median memiliki nilai yang sama, dapat disimpulkan sebaran data merata (kurva normal)

In [84]:
data.isnull().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [85]:
data.duplicated().sum()

np.int64(0)

In [86]:
# hapus missing value
data.dropna(inplace=True)

In [87]:
data.isnull().sum()

Rank            0
Name            0
Platform        0
Year            0
Genre           0
Publisher       0
NA_Sales        0
EU_Sales        0
JP_Sales        0
Other_Sales     0
Global_Sales    0
dtype: int64

In [88]:
#convert year to int
data['Year'] = data['Year'].astype(int)

In [89]:
data['Year']

0        2006
1        1985
2        2008
3        2009
4        1996
         ...
16593    2002
16594    2003
16595    2008
16596    2010
16597    2003
Name: Year, Length: 16291, dtype: int64

In [90]:
data.to_sql('vgsales_clean', con=engine, schema='public', if_exists='replace', index=False)

291

# Business Matrix and Questions
1. Berapa Global sales yang dihasilkan berdasarkan name, genre, platfrom
2. platfrom yang paling banyk digunakan
3. tren genre (date, genre) yang paling populer/laku terjual di tahun tersebut
4. video game nama, genre yang banyak terjual di wilayah amerika utara,
5. video game nama, genre yang banyak terjual di wilayah eropa
6. video game nama, genre yang banyak terjual di wilayah jepang
7. Jumlah total penjualan berdasarkan genre
8. Berapa kali dalam setahun publisher tersebut mengeluarkan game
9. Jumlah penjualan video game di Amerika Utara, Eropa, dan Jepang

In [91]:
# save dataset
data.to_csv("vgsales_clean.csv", index=False)

In [92]:
#Mengubah header kolom sales ke satuan juta copy
data.rename(columns={'NA_Sales': 'NA_Sales (millions_copy)'}, inplace=True)
data.rename(columns={'EU_Sales': 'EU_Sales (millions_copy)'}, inplace=True)
data.rename(columns={'JP_Sales': 'JP_Sales (millions_copy)'}, inplace=True)
data.rename(columns={'Other_Sales': 'Other_Sales (millions_copy)'}, inplace=True)
data.rename(columns={'Global_Sales': 'Global_Sales (millions_copy)'}, inplace=True)

In [93]:
data

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales (millions_copy),EU_Sales (millions_copy),JP_Sales (millions_copy),Other_Sales (millions_copy),Global_Sales (millions_copy)
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [94]:
# 1 10 data global sales paling banyak
data[["Global_Sales (millions_copy)", "Name","Genre", "Publisher"]].head(5)

,Global_Sales (millions_copy),Name,Genre,Publisher
0,82.74,Wii Sports,Sports,Nintendo
1,40.24,Super Mario Bros.,Platform,Nintendo
2,35.82,Mario Kart Wii,Racing,Nintendo
3,33.00,Wii Sports Resort,Sports,Nintendo
4,31.37,Pokemon Red/Pokemon Blue,Role-Playing,Nintendo

In [95]:
# 2. platfrom
data[["Platform" ]].value_counts().head(10)

Platform
DS          2131
PS2         2127
PS3         1304
Wii         1290
X360        1234
PSP         1197
PS          1189
PC           938
XB           803
GBA          786
Name: count, dtype: int64

In [96]:
# 3. Berapa banyak genre
data['Genre'].value_counts()

Genre
Action          3251
Sports          2304
Misc            1686
Role-Playing    1470
Shooter         1282
Adventure       1274
Racing          1225
Platform         875
Simulation       848
Fighting         836
Strategy         670
Puzzle           570
Name: count, dtype: int64

In [97]:
# 4. video game nama, genre yang banyak terjual di wilayah amerika utara
data[["Name", "Genre", "NA_Sales (millions_copy)"]].sort_values(by="NA_Sales (millions_copy)", ascending=False)

                              Name      Genre  NA_Sales (millions_copy)
0                       Wii Sports     Sports                     41.49
1                Super Mario Bros.   Platform                     29.08
9                        Duck Hunt    Shooter                     26.93
5                           Tetris     Puzzle                     23.20
2                   Mario Kart Wii     Racing                     15.85
...                            ...        ...                       ...
16536   Patrician IV: Gold Edition       Misc                      0.00
16535                 Mushi Bugyou     Action                      0.00
16534               Time Travelers  Adventure                      0.00
16533  Metal Gear Solid HD Edition     Action                      0.00
16532      STORM: Frontline Nation   Strategy                      0.00

[16291 rows x 3 columns]

In [98]:
# 5. video game nama, genre yang banyak terjual di wilayah eropa
data[["Name", "Genre", "EU_Sales (millions_copy)"]].sort_values(by="EU_Sales (millions_copy)", ascending=False)

,Name,Genre,EU_Sales (millions_copy)
0,Wii Sports,Sports,29.02
2,Mario Kart Wii,Racing,12.88
3,Wii Sports Resort,Sports,11.01
10,Nintendogs,Simulation,11.00
16,Grand Theft Auto V,Action,9.27
...,...,...,...
16560,Hanasaku Manimani,Adventure,0.00
5453,Digimon World: Dawn / Dusk,Role-Playing,0.00
16594,Men in Black II: Alien Escape,Shooter,0.00
16593,Woody Woodpecker in Crazy Castle 5,Platform,0.00
16592,Plushees,Simulation,0.00

In [99]:
# 6. video game nama, genre yang banyak terjual di wilayah jepang
data[["Name", "Genre", "JP_Sales (millions_copy)"]].sort_values(by="JP_Sales (millions_copy)", ascending=False)

,Name,Genre,JP_Sales (millions_copy)
4,Pokemon Red/Pokemon Blue,Role-Playing,10.22
12,Pokemon Gold/Pokemon Silver,Role-Playing,7.20
1,Super Mario Bros.,Platform,6.81
6,New Super Mario Bros.,Platform,6.50
20,Pokemon Diamond/Pokemon Pearl,Role-Playing,6.04
...,...,...,...
7150,Reactor,Action,0.00
7179,A Boy and His Blob,Platform,0.00
7177,MotoGP 09/10,Racing,0.00
7176,Petz Rescue: Endangered Paradise,Adventure,0.00
7163,Ben 10 Ultimate Alien: Cosmic Destruction,Platform,0.00

In [100]:
# Melihat persentase tiap negara terhadap penjualan global
total_sales_NA = data['NA_Sales (millions_copy)'].sum()
total_sales_EU = data['EU_Sales (millions_copy)'].sum()
total_sales_JP = data['JP_Sales (millions_copy)'].sum()
total_sales_Other = data['Other_Sales (millions_copy)'].sum()
total_sales_Global = data['Global_Sales (millions_copy)'].sum()

In [101]:
# Percentase penjualan di amerika
percent_sales_NA = (total_sales_NA / total_sales_Global) * 100
print(f"NA Sales: {percent_sales_NA:.2f}%")

NA Sales: 49.11%

In [102]:
# Percent penjualan di eropa
percent_sales_EU = (total_sales_EU / total_sales_Global) * 100
print(f"EU Sales: {percent_sales_EU:.2f}%")

EU Sales: 27.31%

In [103]:
# percent sales di Jepang
JP = (total_sales_JP / total_sales_Global) * 100
print(f"JP Sales: {JP:.2f}%")

JP Sales: 14.57%

In [104]:
# Percent other sales
other_sales = (total_sales_Other / total_sales_Global) * 100
print(f"other Sales: {other_sales:.2f}%")

other Sales: 8.95%

In [105]:
# (Tambahan) Groupby tahun, sum penjualan global
yearly_sales = data.groupby('Year')['Global_Sales (millions_copy)'].sum().reset_index().sort_values(by='Global_Sales (millions_copy)',ascending=False)

yearly_sales

    Year  Global_Sales (millions_copy)
28  2008                        678.90
29  2009                        667.30
27  2007                        609.92
30  2010                        600.29
26  2006                        521.04
31  2011                        515.80
25  2005                        458.51
24  2004                        414.01
22  2002                        395.52
33  2013                        368.11
32  2012                        363.49
23  2003                        357.85
34  2014                        337.03
21  2001                        331.47
35  2015                        264.44
18  1998                        256.47
19  1999                        251.27
20  2000                        201.56
17  1997                        200.98
16  1996                        199.15
15  1995                         88.11
14  1994                         79.17
12  1992                         76.16
9   1989                         73.45
36  2016                         70.90
5   1985                         53.94
4   1984                         50.36
10  1990                         49.39
8   1988                         47.22
13  1993                         45.98
6   1986                         37.07
1   1981                         35.77
11  1991                         32.23
2   1982                         28.86
7   1987                         21.74
3   1983                         16.79
0   1980                         11.38
38  2020                          0.29
37  2017                          0.05

In [106]:
#7.Berapa total Video Game yang sudah dikeluarkan publisher
data.groupby(["Publisher"])["Name"].count().sort_values(ascending=False).head(10)

Publisher
Electronic Arts                 1339
Activision                       966
Namco Bandai Games               928
Ubisoft                          918
Konami Digital Entertainment     823
THQ                              712
Nintendo                         696
Sony Computer Entertainment      682
Sega                             632
Take-Two Interactive             412
Name: Name, dtype: int64

In [107]:
#8.Jumlah penjualan video game di Amerika Utara, Eropa, dan Jepang
data["Penjualan di Amerika Utara, Eropa, dan Jepang (millions_copy)"] = data["Global_Sales (millions_copy)"] - data["Other_Sales (millions_copy)"]

data[["Name", "Penjualan di Amerika Utara, Eropa, dan Jepang (millions_copy)"]].head(10)

,Name,"Penjualan di Amerika Utara, Eropa, dan Jepang (millions_copy)"
0,Wii Sports,74.28
1,Super Mario Bros.,39.47
2,Mario Kart Wii,32.51
3,Wii Sports Resort,30.04
4,Pokemon Red/Pokemon Blue,30.37
5,Tetris,29.68
6,New Super Mario Bros.,27.11
7,Wii Play,26.17
8,New Super Mario Bros. Wii,26.36
9,Duck Hunt,27.84

In [108]:
# Filter tahun 2008, ambil kolom Genre, lalu hitung kemunculannya
genre_2008 = data[data['Year'] == 2008]['Genre'].value_counts()

# Menampilkan 5 genre teratas
print(genre_2008.head())

Genre
Action        221
Misc          212
Sports        200
Adventure     166
Simulation    119
Name: count, dtype: int64

## Exploratory Data Analyst